name: Branch Push tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-samples-and-run-tests:
    name: Build samples and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Set up Go
        uses: actions/setup-go@main
        with:
          go-version: '1.22.3'

      - name: Run tests
        run: make test

      - name: Build samples
        run: make buildSamples

      - name: Upload build artifact
        uses: actions/upload-artifact@main
        with:
          name: GoTinyBasicCompiler
          path: build/GoTinyBasicCompiler
